### PR TITLE
Deleted unnecessary checks if certain fields were None

### LINKED ISSUE #11: TransactionDetail has optional fields marked as required
Seen while getting a list of transactions

the following are required, but are in fact optional. This leads to an error (ValueError) when de-serialising a transactions list from YNAB
-memo
-flag_color
-transfer_account_id
-import_id

### PR DESCRIPTION
**Pull request by cjappl**
Closes #11 
#7 
#8

### CODE REVIEW

**Comment by cjappl** [comment]
I think #9  is the much more correct way of doing this, and should be preferred if you have the chance to merge that.

**Review by jazzmoe — APPROVED** [review]

**Comment by jazzmoe** [comment]
I encountered the same issues as in #8 and would appreaciate a merge if @cjappl 's fix solves the issue

Also I am pretty new to coding in python - can I somehow use your fix as a module @cjappl without waiting for a merge in this project?

**Comment by cjappl** [comment]
As a temporary measure, you’re welcome to work off the main branch of my fork. I have recently fixed a few more issues where optional fields would throw.

Based on the state of this main fork, I think the maintainer is a little MIA

**Comment by jazzmoe** [comment]
I'd like to contribute - I actively try to build a useful application linking my different bank accounts to ynab.  Can I somehow download your version to my python package folder. How would that work?

**Comment by cjappl** [comment]
@jazzmoe  you can find my fork here 

https://github.com/cjappl/ynab-python

You can install directly with

`pip install git+https://github.com/cjappl/ynab-python.git`

Or, you can clone the repo, navigate to the top level directory and install locally

```
git clone https://github.com/cjappl/ynab-python
cd ynab-python
pip install -e .
```

If you have any issues, head over to my fork and report it, we can work on it together!

**Comment by jeprecated** [comment]
Lovely, thank you for this easy fix :+1:

**Comment by cjappl** [comment]
Closing, seems like this repo is dead. RIP

**Pull request closed without merging**
